# apiVersion: v1
# kind: Service
# metadata:
#   name: vproapp-service
# spec:
#   ports:
#   - port: 80
#     targetPort: vproapp-port
#     protocol: TCP
#   selector:
#     app: vproapp
#   type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: vproapp-port
    protocol: TCP
    nodePort: 32080  # You can specify any valid port within the range 30000-32767
  selector:
    app: vproapp
